package Gen_div_by_const_fn;
require Exporter;

# Usage :
#   use lib "appropriate_path"
#   use Gen_div_by_const_fn;
#   print gen_div_by_const_fn(7, 32);
#
# This module provides a perl function 'gen_div_by_const_fn'
# that generates a verilog function (e.g. 'div_by_3_fn')
# that implements division by a constant.
#
# The code generated by this module synthesizes better than 
# raw verilog code like :
# ' assign q = x/3; '
#
# An example to illustrate what the generated fn is doing.
# Say we want to divide 996 (0x3E4) by 3.
#  0x3E4 
# =  0x100 * 0x3 + 0x10 * 0xE + 0x1 * 0x4                          // Split input into groups of 4 bits.
# =  0x100 * (1*3 + 0) + 0x10 * (4*3 + 2) + 0x1 * (1*3 + 1)        // Divide each 4bit number by 3 using a LUT. Get respective q,r.
# =  0x100 * (1*3 + 0) + (3 * (0x10*4 + 0x1*1) + (0x10*2 + 0x1*1)) // Combine q's and r's in pairs.
# =  0x100 * (1*3 + 0) + (3 * 0x41 + 0x21)                         // ''
# =  0x100 * (1*3 + 0) + (3 * 0x41 + (3*0xB + 0))                  // Divide pair of r's by 3 and figure out the part to add to the combined q and the net remainder.
# =  0x100 * (1*3 + 0) + (3 * (0x41 + 0xB) + 0))                   // Adjust the combined q by the adjustment from the previous step.
# =  0x100 * (1*3 + 0) + (3 * 0x4C + 0))                           // ''
# =  0x14C * 3 + 0;                                                // Keep doing tree reduction until we reach a final q and r representing the whole original input.
# => q = 0x14C , r = 0                                             // We are done.

our @ISA = qw(Exporter);
our @EXPORT = qw(gen_div_by_const_fn);
our $VERSION = 1.00;

sub clog2 {
  my ($n) = @_;
  my $l = int( (log($n)/log(2)) + 0.99999 );
  return $l;
}

sub gen_div_by_const_fn{
  my ($N, $ibits, $piece_sz, $obits, $fname) = @_;
  # N        = constant to divide by.
  # ibits    = input bits (default = 32)
  # piece_sz = starting unit of tree in bits (optional)
  # obits    = output quotient bits (optional)
  # fname    = function name (optional).
  #
  #  piece_sz has a reasonable default, but is worth playing with if you need
  #  to improve QOR.  The effects of modifying piece_sz are non-linear and
  #  non-monotonic.  This is because it affects both the work in done in each
  #  layer and the number of layers.

  die "N must be defined. N=$N." unless (defined $N);
  $ibits //= 32;
  $obits //= &clog2( 1.0*(2**$ibits)/$N );
  $fname //= "div_by_${N}_fn";

  my $ibits_m1 = $ibits - 1;
  my $obits_m1 = $obits - 1;

  # Factorize N into power of 2 (wizard) and non-power of 2(muggle).
  my $Nw = 1;
  while (($N % ($Nw * 2)) == 0) { $Nw *= 2; }
  my $Nm = $N/$Nw;

  my $lN = clog2($N);
  my $lNw = clog2($Nw);
  my $lNm = clog2($Nm);
  my $lN_m1 = $lN - 1;
  my $lNw_m1 = $lNw - 1;
  my $lNm_m1 = $lNm - 1;

  # Figure out piece_sz and num_pieces
  $piece_sz //= $lNm + 2;
  my $num_pieces = 1;
  $num_pieces *= 2 while ($num_pieces * $piece_sz < $ibits);

  # Header
  my $return_type = "div_result_${ibits}_${N}_t";
  my $output = "";
  $output .= <<XYZ;
  typedef struct packed {
    logic [${obits_m1}:0] \t q; // quotient
    logic [${lN_m1}:0] \t r; // remainder
  } $return_type;

  function $return_type $fname ( logic [${ibits_m1}:0] x );
   $return_type result;
   logic [${ibits_m1}:0] \t wq;
XYZ
  $output .= <<XYZ if ($lNw > 0);
   logic [${lNw_m1}:0] \t wr;
XYZ

  # Declarations
  my ($np, $ps, $i) = ($num_pieces, $piece_sz, 0);
  while ($np >= 1) {
    my $np_m1 = $np - 1;
    my $ps_m1 = $ps - 1;
    $output .= <<XYZ;
   logic [$np_m1:0][${ps_m1}:0] \t q_${i};
XYZ
    if ($i > 1) {
      $output .= <<XYZ;
   logic [$np_m1:0][${ps_m1}:0] \t aq_${i};
XYZ
    }
    if ($i > 0) {
      $output .= <<XYZ;
   logic [$np_m1:0][${lNm_m1}:0] \t r_${i};
XYZ
      $np /= 2; $ps *= 2; 
    }
    $i++;
  }

  # End header
  $output .= <<XYZ;
  begin

XYZ

  if ($Nw > 1) {
  $output .= <<XYZ;
    // Handle the power of 2 part first.
    wq = x[$ibits_m1:$lNw];
    wr = x[$lNw_m1:0];
XYZ
  } else {
  $output .= <<XYZ;
    wq = x;
XYZ
  }

  if ($Nm > 1) {
    # Calculate first layer : divide each piece by $N.
    $output .= <<XYZ;

    // Now work on the hard part : non-power of 2.
    // Separate input into $num_pieces pieces of size $piece_sz bits each.
    q_0 = wq;

    // Divide each piece by $Nm 
    q_1 = 0; r_1 = 0;
    for (int i = 0; i < $num_pieces; i++) begin
      case(q_0[i])
XYZ
    foreach $i (1 .. (2**$piece_sz - 1)) {
      my $i_div_Nm = int ($i / $Nm);
      my $i_mod_Nm = $i % $Nm;
      $output .= <<XYZ;
        $i : begin q_1[i] = $i_div_Nm; r_1[i] = $i_mod_Nm; end
XYZ
    }
    $output .= <<XYZ;
      endcase
    end

XYZ

    # Refine result as many times as needed.
    my ($np, $ps, $j) = ($num_pieces, $piece_sz, 1);
    while ($np > 1) {
      $np /= 2; $ps *= 2; $j++;
      my $k = $j - 1;
      $output .= <<XYZ;
    // Refine result for each pair of pieces
    for (int i = 0; i < $np; i++) begin
      case({r_${k}[2*i+:2]})
XYZ
      foreach my $rem1 (1 .. ($Nm - 1)) {
        foreach my $rem2 (0 .. ($Nm - 1)) {
          my $total_rem = ($rem1 << ($ps/2)) + $rem2;
          my $total_rem_div_Nm = int($total_rem / $Nm);
          my $total_rem_mod_Nm = $total_rem % $Nm;
          $output .= <<XYZ;
        {${lNm}'d${rem1}, ${lNm}'d${rem2}} : begin aq_${j}[i] = $total_rem_div_Nm; r_${j}[i] = $total_rem_mod_Nm; end // rem = $total_rem = $total_rem_div_Nm * $Nm + $total_rem_mod_Nm
XYZ
        }
      }
      $output .= <<XYZ;
        default      : begin aq_${j}[i] = 0; r_${j}[i] = r_${k}[2*i]; end
      endcase
      q_${j}[i] = q_${k}[2*i+:2] + aq_${j}[i];
    end

XYZ
    }

    # Final hookup.
    $output .= <<XYZ;
    result.q = q_${j}[0];
XYZ
    if ($Nw > 1) {
      $output .= <<XYZ;
    result.r = r_${j}[0] << $lNw + wr;
XYZ
    } else {
      $output .= <<XYZ;
    result.r = r_${j}[0];
XYZ
    }
  } else {
    $output .= <<XYZ;

    result.q = wq;
    result.r = wr;
XYZ
  }

  # Footer
  $output .= <<XYZ;
    return result;
  end
  endfunction
XYZ

  return $output;
}

1;

